services:
  - type: web
    name: apexafrika-web
    runtime: docker
    repo: https://github.com/winstone-1/Apexafrika-backend
    plan: free
    dockerfilePath: ./Dockerfile.prod
    dockerContext: .
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: ALLOWED_HOSTS
        value: apexafrika-backend.onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: apexafrika-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: apexafrika-redis
          type: redis
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_SECRET_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_MERCHANT_EMAIL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://apexafrika.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://apexafrika.com,https://www.apexafrika.com,https://api.apexafrika.com

databases:
  - name: apexafrika-db
    plan: free
    databaseName: apexafrika_db
    user: apexafrika_user

redis:
  - name: apexafrika-redis
    plan: free
    maxmemoryPolicy: noeviction
