# Generated by Django 5.1.4 on 2026-07-18 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={"ordering": ["tier", "name"]},
        ),
        migrations.AddField(
            model_name="achievement",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="required_community_posts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="achievement",
            name="required_teams",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="achievement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="is_equipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="progress",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="category",
            field=models.CharField(
                choices=[
                    ("TOURNAMENT", "Tournament"),
                    ("MATCH", "Match"),
                    ("COMMUNITY", "Community"),
                    ("STREAK", "Streak"),
                    ("MILESTONE", "Milestone"),
                    ("SPECIAL", "Special"),
                    ("TEAM", "Team"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="tier",
            field=models.CharField(
                choices=[
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                    ("DIAMOND", "Diamond"),
                    ("LEGENDARY", "Legendary"),
                ],
                default="BRONZE",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["category"], name="achievement_categor_a7059b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["tier"],
                name="achievement_tier_fd5f87_idx"),
        ),
        migrations.AddIndex(
            model_name="userachievement",
            index=models.Index(
                fields=["user", "-unlocked_at"], name="achievement_user_id_0abd7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userachievement",
            index=models.Index(
                fields=["is_equipped"], name="achievement_is_equi_800dc8_idx"
            ),
        ),
    ]
