# Generated by Django 5.1.4 on 2026-07-18 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_type', models.CharField(choices=[('ESSENTIAL', 'Essential'), ('ANALYTICS', 'Analytics'), ('MARKETING', 'Marketing'), ('PREFERENCE', 'Preference')], max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TERMS', 'Terms of Service'), ('PRIVACY', 'Privacy Policy'), ('COOKIE', 'Cookie Policy'), ('COMMUNITY', 'Community Guidelines'), ('GDPR', 'GDPR Compliance'), ('CCPA', 'CCPA Compliance')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('version', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('effective_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('type', 'language', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('TERMS', 'Terms of Service'), ('PRIVACY', 'Privacy Policy'), ('COOKIE', 'Cookie Policy'), ('MARKETING', 'Marketing'), ('DATA_PROCESSING', 'Data Processing'), ('COMMUNITY', 'Community Guidelines')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='legal.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consented_at'],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
