# Generated by Django 5.1.4 on 2026-07-18 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_reminders', models.BooleanField(default=True)),
                ('match_updates', models.BooleanField(default=True)),
                ('registration_alerts', models.BooleanField(default=True)),
                ('post_comments', models.BooleanField(default=True)),
                ('post_likes', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('payment_confirmation', models.BooleanField(default=True)),
                ('prize_notifications', models.BooleanField(default=True)),
                ('system_updates', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TOURNAMENT', 'Tournament'), ('MATCH', 'Match'), ('PAYMENT', 'Payment'), ('COMMUNITY', 'Community'), ('SYSTEM', 'System'), ('ACHIEVEMENT', 'Achievement'), ('REMINDER', 'Reminder')], max_length=20)),
                ('channel', models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('IN_APP', 'In-App')], default='IN_APP', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx')],
            },
        ),
    ]
